name: city
options:
    bundleIdPrefix: "com.dev-factory"
    deploymentTarget: 16
    developmentLanguage: "en"
    postGenCommand: pod install
configs:
    debug: debug
    preprod: release
    release: release
configFiles:
    debug: configuration/debug.xcconfig
    release: configuration/release.xcconfig
targets:
    city:
        type: application
        platform: iOS
        deploymentTarget: 16.0
        sources:
            - city
        info:
            path: city/Info.plist
            properties:
                UILaunchStoryboardName: LaunchScreen
                BASE_URL: $(BASE_URL)
        entitlements:
            path: city/city.entitlements
        settings:
            base:
                CURRENT_PROJECT_VERSION: 1
                MARKETING_VERSION: 0.0.1
                INFOPLIST_FILE: city/Info.plist
            debug:
                DEV_BUILD_SETTINGS: debug
            configs:
                debug:
                    DEV_BUILD_SETTINGS: debug
                preprod:
                    PREPROD_BUILD_SETTINGS: preprod
                release:
                    RELEASE_BUILD_SETTINGS: release
        scheme:
            testTargets:
            - cityTests
        configFiles:
            debug: configuration/debug.xcconfig
            release: configuration/release.xcconfig
        postBuildScripts:
            - path: configuration/swiftgen.sh
              name: SwiftGen
    cityTests:
        type: bundle.unit-test
        platform: iOS
        sources:
            - path: cityTests
        dependencies:
            - target: city
        info:
            path: cityTests/Info.plist
            properties:
                UILaunchStoryboardName: LaunchScreen
                BASE_URL: $(BASE_URL)
    cityUITests:
        type: bundle.ui-testing
        platform: iOS
        sources:
            - path: cityUITests
        
            

      
